### ISSUE TITLE
"d3plus.Network is not a constructor"

### ISSUE THREAD

**Issue by mitevpi** [d3plus/d3plus-network#47]
I've been trying to use d3plus 2.0 for a number of visualizations, but every time I try to use the new module/class structure, I get an error of "X" is not a constructor. The images below show the failure which is specific to the network class, but I get the same failure whenever I try any other class from the 2.0 [examples page](http://d3plus.org/examples/).

This is my basic script and failure:
![d3pluserror](https://user-images.githubusercontent.com/25568566/46222938-e9e06580-c31f-11e8-8fb7-a76b7dcae263.png)

This is my basic HTML file:
![image](https://user-images.githubusercontent.com/25568566/46222959-f9f84500-c31f-11e8-8c7f-e07776a05a2a.png)

This is my package.json (showing the 2.0 version installed by npm):
![image](https://user-images.githubusercontent.com/25568566/46223007-13998c80-c320-11e8-9209-c753869db265.png)

Is this an error on my part (very likely), or is something else wrong?

**Comment by davelandry** [comment]
For vanilla environments, we recommend using the hosted compiled version:

```html
<script src="https://d3plus.org/js/d3plus.v2.0.0-alpha.17.full.min.js"></script>
```

`"../node_modules/d3plus/d3plus.js"` is not a file that exists. There may be a file in `"../node_modules/d3plus/build/"` that is usable, but your mileage may vary.

**Comment by davelandry** [comment]
Additionally, if you're only using the Network, only load this library:

```html
<script src="https://d3plus.org/js/d3plus-network.v0.5.full.min.js"></script>
```

**Comment by mitevpi** [comment]
Thanks - confirming that this worked, appreciate the response.
