### ISSUE TITLE
Network is not displayed if string id is used in "source" and "target" keys in links

### ISSUE THREAD

**Issue by zastupailo** [d3plus/d3plus-network#48]
### Expected Behavior
Network is displayed if the `source` and `target` keys in each link map to a _String_ value matching the `id` of the node.

```js
var nodes = [
  {id: "alpha", x: 1, y: 1},
  {id: "beta", x: 6, y: 1},
  {id: "gamma", x: 4, y: 4}
];

var links = [
  {source: "alpha", target: "beta"},
  {source: "alpha", target: "gamma"}
];

new d3plus.Network()
  .links(links)
  .nodes(nodes)
  .render();
```

### Current Behavior
Network is not displayed, exception in console.
```
d3plus-network.v0.5.full.min.js:31 Uncaught TypeError: Cannot read property 'id' of undefined
    at d3plus-network.v0.5.full.min.js:31
    at Array.reduce (<anonymous>)
    at t [as _draw] (d3plus-network.v0.5.full.min.js:31)
    at hg._call (d3plus-network.v0.5.full.min.js:31)
    at pg (d3plus-network.v0.5.full.min.js:7)
    at hg.awaitAll (d3plus-network.v0.5.full.min.js:7)
    at t [as render] (d3plus-network.v0.5.full.min.js:31)
    at window.onload ((index):44)
```

### Steps to Reproduce
1. Create a JSFiddle out of [this](https://d3plus.org/examples/d3plus-network/getting-started/) example.
2. Replace indexes of nodes in `links` with _String_ values of the `id` key in nodes.
3. Example: https://jsfiddle.net/ucdx801f/

**Comment by Vidyut** [comment]
I am not able to get it to work any way. Anyone know a fix?

**Comment by davelandry** [comment]
@Vidyut until the bug is fixed, you need to reference nodes by their index in their array: https://jsfiddle.net/aedwfp4c/
