### ISSUE TITLE
improve Sankey algorithm

### ISSUE THREAD

**Issue by cnavarreteliz** [d3plus/d3plus-network#57]
In this moment, Sankey diagram works fine, but it's very restrictive with the data format. For example, you need passing a variable with `nodes` and `links`, you cannot passing a `PATH URL` for links / nodes.

I propose improve how the Sankey diagram works, simplifying at least the data passed into `links` attribute.

**Comment by davelandry** [comment]
@cnavarreteliz the `nodes` and `links` methods already support providing a URL instead of a data object, as seen here: https://github.com/d3plus/d3plus-network/blob/master/src/Sankey.js#L270-L279

Is there something else you'd like it to do?
