### ISSUE TITLE
Displaying images on nodes

### ISSUE THREAD

**Issue by ewg118** [d3plus/d3plus-network#76]
I have a pretty extreme edge use case, where I am using the d3plus network to create a graph of the links between symbols that appear in conjunction with each other on ancient Greek coins. These symbols have SVG representations, and ideally I would like to display them in some way within the network visualization. I attempted the following in the config:

    label: function (node) {
                if (node.hasOwnProperty('image')) {
                    return node.label + ' <img src="' + node.image + '" style="width:16px"/>';
                } else {
                    return node.label;
                }
    }

Because the d3plus visualization is SVG itself, injecting a bit of HTML into `label` doesn't do anything, although surprisingly the tooltip will display the SVG graphic (see attached image).

Is there any solution for this? Ideally, I would like to embed the SVG graphic into the node circle, but displaying the SVG in the tooltip is acceptable enough. However, as you can see in the screenshot, the `<img>` tag is just displayed as text in the node. Is it possible to control the tooltip more directly, or is it inextricably bound to the `label`?

![Screenshot from 2021-06-04 10-17-27](https://user-images.githubusercontent.com/563187/120817219-8753b480-c51f-11eb-9cfd-17b6053818be.png)

**Comment by ewg118** [comment]
Update: I've figured out how to us tooltipConfig in order to display the SVG directly in the tooltip, but I'm still looking for a way to display the SVG within the node bubble, if at all possible. I tried something like this: https://stackoverflow.com/questions/5451135/embed-svg-in-svg but it doesn't have the intended effect. Looking at the source in my browser, I see that the `label` property is placed into the HTML `aria-label` attribute. I suppose what I want to is embed the `<image>` into the `<circle>` within the SVG generated dynamically by d3plus.

**Comment by davelandry** [comment]
@ewg118 you're looking for the `backgroundImage` property of `shapeConfig`. Any shape, whether it's circles in a Network or rectangles in a Treemap can have background images (separate from labels): http://d3plus.org/examples/d3plus-hierarchy/background-image/

**Comment by ewg118** [comment]
Thanks! I got it working.
