### ISSUE TITLE
[rendering] issue in bubbles opacity/order

### ISSUE THREAD

**Issue by palamago** [d3plus/d3plus-network#78]
### Expected Behavior
Like oec in prod:
![Screen Shot 2021-06-15 at 15 10 09](https://user-images.githubusercontent.com/1203432/122102444-ccaf9600-cdeb-11eb-9dfc-dc5e3811f647.png)

### Current Behavior
Like oec in dev:
![Screen Shot 2021-06-15 at 15 09 58](https://user-images.githubusercontent.com/1203432/122102465-d2a57700-cdeb-11eb-8e4f-4c40d415b638.png)

### Steps to Reproduce (for bugs)

1. Go to france profile
2. Product space section
3. Click on `Delivery Trucks` bubble

### Your Environment

* Browser Name: chrome
* Operating System and Version: mac os

**Comment by davelandry** [comment]
Core d3plus bug has been fixed, I will open a PR for OEC updating the dependency, and make any CMS adjustments that are needed 🤞🏻
